display_startup_errors = Off
display_errors = Off
log_errors = On
error_log = "php-error.log"

; No extension directives here to avoid loading unavailable DLLs during preview

[Date]
date.timezone = "UTC"
